### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#26]
### Description

Use [dotenv](https://www.npmjs.com/package/dotenv) to store the location of the *Poster-Service* and *Metadata-Service*.

### Tasks

- [x] add dotenv dependency
- [x] create `.env.templete`
- [x] update `README.md`
- [x] verify that the environment variables can be read by the application
