### ISSUE TITLE
Provide Movie Query

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#27]
### Description

Provide a query to get a movie. Either return the movie specified by the provided `imdbid` or return a random movie if no id is present.

### Tasks

- [x] extend the **schema** with the required fields (imdbid, title, posterPath, releaseYear)
- [x] extend the **service** to query the **metadata-service** to fetch information about a specific or random movie
- [x] extend the **service** to query the **poster-service** to fetch the movie poster of a specific movie
- [x] update the **resolver**
- [x] write unit test for the service
- [x] write e2e test for the resolver
- [x] update **README** with API usage

### User Stories

- [Blurred Poster Screen](https://github.com/kwizapp/kwiz/issues/9)
- [Story: Trivia Screen](https://github.com/kwizapp/kwiz/issues/14)

### Sketch

```
{
  query movie(imdbId?) {
    imdbid
    title
    posterPath
    releaseYear
  }
}
```

**Comment by alexscheitlin** [comment]
Waiting for [Always returns a random movie #13 - Metadata-Service](https://github.com/kwizapp/metadata-service/issues/13) to be fixed.

Does someone have input on how to make the e2e test pass? I was not able to figure it out.
