### ISSUE TITLE
Provide Multiple Movies

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#28]
### Description

Provide a query to get `n` random movies given an `imdbid`.

### Tasks

- [x] extend the **service** to query the metadata-service to fetch information about `n` random movies
- [x] update the **resolver**
- [x] write unit test for the service
- [x] write e2e test for the resolver
- [x] update **README** with API usage

### User Stories

- [Question Screen ("Title")](https://github.com/kwizapp/kwiz/issues/11)

### Sketch

```
{
  query movie(imdbId?) {
    ...
    randomMovies(num=3) {
      imdbid
      ...
    }
  }
}
```
or

```
{
  query randomMovies(imdbId, num=3) {
    imdbid
    ...
  }
}
```
