### ISSUE TITLE
Provide Different Movies

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#29]
### Description

Provide a query to get `n` different movies released in different years given an `imdbid`.

### Tasks

- [x] extend the **service** to query the metadata-service to fetch information about `n` different movies
- [x] update the **resolver**
- [x] write unit test for the service
- [x] write e2e test for the resolver
- [x] update **README** with API usage

### User Stories

- [Question Screen ("Bonus")](https://github.com/kwizapp/kwiz/issues/15)

### Sketch

```
{
  query movie(imdbId?) {
    ...
    differentMovies(num=2) {
      imdbid
      ...
    }
  }
}
```
or

```
{
  query differentMovies(imdbId, num=2) {
    imdbid
    ...
  }
}
```
