### ISSUE TITLE
Calculate Scores for "Poster Guessing" Question

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#30]
### Description

Calculate the scores for the guessing of a movie poster based on the correctness of the answer and the remaining time.

- If the answer is incorrect, `0` points are awarded and the player loses one life.
- If the answer is correct, the points are calculated based on the remaining seconds.

### Tasks

- [x] extend the **service** to calculate points between `0` and `n`
- [x] update the **resolver**
- [x] write unit test for the service
- [x] write e2e test for the resolver
- [x] update **README** with API usage

### User Stories

- [Question Screen ("Title")](https://github.com/kwizapp/kwiz/issues/11)

### Sketch

```
{
  query scoreTitleResponse(imdbId, selectedTitle, secondsRemaining) -> points
}

```
