### ISSUE TITLE
Calculate Scores for "Bonus" Question

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/nest-api#31]
### Description

Calculate the scores for the bonus question based on the scores of the previous "poster guessing" question.

- If the answer is incorrect, no points are awarded and the player loses the points from the "guessing question" ("doubble or nothing").
- If the answer is correct, the points from the "guessing question" are doubbled.

### Tasks

- [x] extend the **service** to calculate points between `0` and `n`
- [x] update the **resolver**
- [x] write unit test for the service
- [x] write e2e test for the resolver
- [x] update **README** with API usage

### User Stories

- [Question Screen ("Bonus")](https://github.com/kwizapp/kwiz/issues/15)

### Sketch

```
{ 
  query scoreYearResponse(imdbId, selectedYear, currentPoints) -> points
}
```
